### PR TITLE
Added better styling for preview and logs panel

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Fixed:

#658 
#649

### CODE REVIEW

**Review by fatchat — CHANGES_REQUESTED** [review]
preview works as requested
cast data types no longer resetting after blurring type fields
logs looks great... BUT
logs are not scrolling though

**Comment by mdshamoon** [comment]
@fatchat fixed now. Please check.

**Comment by Ishankoradia** [comment]
@mdshamoon when the logs are running (loading), the tabs (preview/logs) are not visible which are visible in staging.

**Comment by mdshamoon** [comment]
@Ishankoradia fixed this. I should do better testing. Will take care moving forward.

**Review by fatchat — APPROVED** [review]

**Pull request merged**
