### PR TITLE
issue/735-is-the-password-reset-email-messing-up-the-token

### PR DESCRIPTION
**Pull request by himanshudube97**
- Issue and probable cause explained here:-> https://github.com/DalgoT4D/webapp/issues/987
- solving the issue by using CSR while accessing the token from the url.

### CODE REVIEW

**Comment by himanshudube97** [comment]
- so we cant use teh useSearchParams() as its a **hook** provided by the nextjs. So hooks cant be called inside a function. Thats why I used the URLSearchParams.
And just wanted to confirm, did it worked on the deployed staging? Was the error resolved by this code?

**Comment by fatchat** [comment]
oh i see... wow i had no idea

i have deployed it on staging, and i was able to reset my password 

anything you want to check before i merge?

**Comment by fatchat** [comment]
oh you have to change the error toast

**Comment by himanshudube97** [comment]
-Now i have changed the error toast and pushed the changed.

**Review by fatchat — APPROVED** [review]

**Pull request merged**
