### PR TITLE
1088 ai summary should not be clickable for successful runs and there should be a notification that this feature only works for failures

### PR DESCRIPTION
**Pull request by himanshudube97**
- Conditionally rendering the Ai summary button for the failed logs.
- Changed the conditions to show the load more button.

### CODE REVIEW

**Comment by fatchat** [comment]
@himanshudube97 you have to do this for the orchestrate page as well

**Comment by himanshudube97** [comment]
> @himanshudube97 you have to do this for the orchestrate page as well



> @himanshudube97 you have to do this for the orchestrate page as well



> @himanshudube97 you have to do this for the orchestrate page as well

@fatchat added and pushed.

**Comment by himanshudube97** [comment]
> @himanshudube97 you have to do this for the orchestrate page as well

@fatchat added for the orchestrate.

**Comment by fatchat** [comment]
works well. i think we can remove `*For AI summary of failed logs press the AI Summary button`

**Review by fatchat — APPROVED** [review]

**Pull request merged**
