### PR TITLE
Added permissions for all roles

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Added permissions for all roles

### CODE REVIEW

**Comment by Ishankoradia** [comment]
@mdshamoon the invitation flow needs to be updated with the new set of `v1` apis. I think there are 3 of them `POST v1/organizations/users/invite/`, `POST /v1/organizations/users/invite/accept/`  and fetching invitations `GET /v1/users/invitations/`

**Comment by mdshamoon** [comment]
@Ishankoradia added these 3 API. I can also see invitation resend and delete APIs. Do we need to update those as well?

**Comment by Ishankoradia** [comment]
> @Ishankoradia added these 3 API. I can also see invitation resend and delete APIs. Do we need to update those as well?

Yes please. We will remove the deprecated apis in our next cleanup

**Comment by fatchat** [comment]
# Tests

User management:  page often crashes in `ManageUsers.tsx:79` but I couldn't figure out the pattern... a few times reloading solved it but not always

## Guest role 
- User management: Invite User Button disabled, Action menus not visible on `ui-testing`, visible and disabled on `dalgo-postgres`
- Pipeline overview: visible and log fetching works
- Ingest | Connections: New Connection and Sync buttons disabled. Fetch Logs works. Action menu disabled
- Ingest | Sources: Buttons and Action menus disabled
- Ingest | Your Warehouse: Buttons disabled
- Transform: New Task and Execute buttons disabled. Action menus disabled. Go To Workflow works
- Transform | Workflow Canvas: Run disabled, action panel never appears, preview works, source tree is navigable, cannot add to canvas, cannot sync sources. But deleting a node works @mdshamoon  #bug
- Orchestrate: New Pipeline is disabled, Run and Actions menus are disabled. Log fetching works

## Analyst role
- User management: unable to access page; crashes in `ManageUsers.tsx:79`
- Pipeline overview: visible and log fetching works
- Ingest | Connections: New Connection disabled, Sync button enabled. Fetch Logs works. Action menu disabled
- Ingest | Sources: Buttons and Action menus disabled
- Ingest | Your Warehouse: Buttons disabled
- Transform: New Task and Execute buttons enabled. Action menus enabled. Go To Workflow works
- Transform | Workflow canvas: Editable: side panel opens, delete works. Run button is disabled. sync-sources works, adding sources to canvas works
- Orchestrate: New pipeline disabled, Run disabled, Actions menu disabled. Logs can be fetched

## Pipeline Manager role
- User management: Buttons and Actions menu disabled
- Pipeline overview: Clicking menu item had no effect on `dalgo-postgres` org but worked on `ui-testing`
- Ingest | Connections: New connection disabled, Sync disabled, Actions menu disabled on `dalgo-postgres` org but worked on `ui-testing`. Logs worked @mdshamoon
- Ingest | Sources: Buttons and Action menus disabled on `dalgo-postgres` org but worked on `ui-testing`
- Ingest | Your Warehouse: Buttons disabled
- Transform: New Task and Execute buttons enabled. Action menus enabled. Go To Workflow works
- Transform | Workflow Canvas: Run disabled, action panel never appears, preview works, source tree is navigable, cannot add to canvas, cannot sync sources - on `dalgo-postgres` org but worked on `ui-testing`. But deleting a node works @mdshamoon  #bug
- Orchestrate: New pipeline, Run, Actions menu work on `ui-testing`. Logs are fetched

## Account Manager
- User management: Buttons and Actions menu enabled
- Pipeline overview: worked on `ui-testing`
- Ingest | Connections: New connection enabled, Sync enabled, Actions menu enabled on `ui-testing`. Logs worked 
- Ingest | Sources: Buttons and Action menus enabled on `ui-testing`
- Ingest | Your Warehouse: Buttons enabled on `ui-testing`
- Transform: New Task and Execute buttons enabled. Action menus enabled. Go To Workflow works
- Transform | Workflow Canvas: Run enabled, action panel appears, preview works, source tree is navigable, can add to canvas, can sync sources - on `ui-testing`. deleting a node works
- Orchestrate: New pipeline, Run, Actions menu work on `ui-testing`. Logs are fetched

## Super Admin
- Same as account manager, can also create new org
- todo: data preview should not work (we will implement this in the backend as well)

**Comment by mdshamoon** [comment]
@fatchat updated with all the fixes. The PR is ready for review

**Comment by fatchat** [comment]
Figured out the issue I was having with the `dalgo-postgres` org - had two OrgUsers for some reason

Now `dalgo-postgres` is behaving the same as `ui-testing`

**Comment by fatchat** [comment]
Went through the tests from the long comment above - all bugs reported have been fixed and the application works as described above

@nairabhishek73 over to you - you may test on staging. also please verify that what i recorded above is what we want

**Review by fatchat — APPROVED** [review]

**Pull request merged**
