### PR TITLE
Fix: overflowing components when drawer is collapsed

### PR DESCRIPTION
**Pull request by Snehil-Shah**
## Summary

Before: 

image

## Test Plan

After:

after_arrow

### CODE REVIEW

**Comment by Snehil-Shah** [comment]
@fatchat I am on chrome, even the links documentation and privacy policy links were overflowing in my case

**Comment by Ishankoradia** [comment]
This is good catch @Snehil-Shah @fatchat  . Although i dont see anything overflowing in my browser `(chrome Version 123.0.6312.124 (Official Build) (arm64))`. 
But in the collapsed state, when i hover below to where the `privacy policy` could have been, i am able to click and open the page. Clearly something is wrong.

**Comment by fatchat** [comment]
how interesting... i'm happy to merge this 

@mdshamoon this seems to be a bug for some browsers / browser versions... any comments

**Comment by Ishankoradia** [comment]
> @Ishankoradia Can you confirm if you are able to hover over the _not visible_ arrow keys as well? This PR should fix that. Although I wonder what's causing this discrepancy between my browser and yours...

Yes i am able to hover over the non visible elements.

**Comment by mdshamoon** [comment]
@fatchat we have browserstack subscription. Its best to check there as well. @Snehil-Shah can you let me know your chrome version?

The changes looks good otherwise.

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
