### PR TITLE
Next js v14 update

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Next js v14 update

### CODE REVIEW

**Comment by Ishankoradia** [comment]
@mdshamoon should we release this on staging for a 1-2 days ?

**Comment by mdshamoon** [comment]
@Ishankoradia makes sense. Lets do this today.

**Comment by Ishankoradia** [comment]
@mdshamoon done (on staging).
Upraded node to `18.20.3` and corresponding npm to `10.7.0`.

**Review by Ishankoradia — APPROVED** [review]

**Comment by Ishankoradia** [comment]
@mdshamoon merging this. Updated next on beta also.

**Comment by fatchat** [comment]
@Ishankoradia @mdshamoon 
when you upgrade things please record the commands you used in the ticket

on production i ran `nvm install 18.20.3` which upgraded npm to `10.7.0`

pm2 was using the `18.16` so i added `interpreter: "/home/ddp/.nvm/versions/node/v18.20.3/bin/node"` to the top of the `ecosystem.config.js` file

before that i ran `yarn global add pm2@latest` and `pm2 update` which had no effect that i could see

when versions change please also update `platform-infra`: https://github.com/DalgoT4D/platform_infra/issues/38

**Comment by Ishankoradia** [comment]
> @Ishankoradia @mdshamoon when you upgrade things please record the commands you used in the ticket
> 
> on production i ran `nvm install 18.20.3` which upgraded npm to `10.7.0`
> 
> pm2 was using the `18.16` so i added `interpreter: "/home/ddp/.nvm/versions/node/v18.20.3/bin/node"` to the top of the `ecosystem.config.js` file
> 
> before that i ran `yarn global add pm2@latest` and `pm2 update` which had no effect that i could see
> 
> when versions change please also update `platform-infra`: [DalgoT4D/platform_infra#38](https://github.com/DalgoT4D/platform_infra/issues/38)

@fatchat i mentioned in the above comment that I had to delete the pm2 process and create a new one to start the webapp from new node version. pm2 doesn't understand the new version somehow.

**Pull request merged**
