### PR TITLE
Added menu for elementary report

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

- Added menu for elementary report. 
- Added an env variable NEXT_SHOW_ELEMENTARY_MENU that shows/hides the item in the menu.

**Remaining**: 
- Icon to be updated

### CODE REVIEW

**Comment by fatchat** [comment]
@mdshamoon  to get the report generation time from the `dbt/make-elementary-report/` response

https://github.com/DalgoT4D/DDP_backend/pull/660

**Comment by mdshamoon** [comment]
> @mdshamoon to get the report generation time from the `dbt/make-elementary-report/` response
> 
> [DalgoT4D/DDP_backend#660](https://github.com/DalgoT4D/DDP_backend/pull/660)

Thanks @fatchat . You also mentioned a regenerate report button and API. Are you going to add that also?

**Comment by fatchat** [comment]
> > @mdshamoon to get the report generation time from the `dbt/make-elementary-report/` response
> > [DalgoT4D/DDP_backend#660](https://github.com/DalgoT4D/DDP_backend/pull/660)
> 
> Thanks @fatchat . You also mentioned a regenerate report button and API. Are you going to add that also?

yes, will do via another backend PR, probably tomorrow

**Comment by fatchat** [comment]
here it is: https://github.com/DalgoT4D/DDP_backend/pull/662

**Comment by fatchat** [comment]
@mdshamoon 

variable is `NEXT_PUBLIC_SHOW_ELEMENTARY_MENU` or `NEXT_SHOW_ELEMENTARY_MENU`

should be a top-level menu item, not under "analysis" though you can double-check with nair

**Comment by mdshamoon** [comment]
> @mdshamoon
> 
> variable is `NEXT_PUBLIC_SHOW_ELEMENTARY_MENU` or `NEXT_SHOW_ELEMENTARY_MENU`
> 
> should be a top-level menu item, not under "analysis" though you can double-check with nair

Updated the variable, its NEXT_PUBLIC_SHOW_ELEMENTARY_MENU
Also made the menu item at top level

**Comment by fatchat** [comment]
very nice, i pushed a minor change. will test against backend once that is merged

**Review by Ishankoradia — APPROVED** [review]

**Pull request merged**
