### PR TITLE
Added edit feature for github URL for transform

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Added edit feature for github URL for transform

### CODE REVIEW

**Comment by fatchat** [comment]
at initial setup time let's not show the `edit` button

image

**Comment by fatchat** [comment]
after editing the target schema, the screen needs to be refreshed to reflect the change

**Comment by fatchat** [comment]
after changing the remote github repo url, the backend correctly resets the repo dir and clones the new repo. but something went wrong in sending the celery task id back to the frontend, so when the frontend polled for progress it received a `400` "no such task id"

Redis contained the correct hash-val though... i.e. `hget("clone-github-repo-rc-local-airbyte-pos", '<uuid>')` contained

`b'[{"message": "cloned git repo", "status": "completed"}]'`

so either django queried incorrectly or there is a timing issue

**Comment by mdshamoon** [comment]
@fatchat this is ready for review.

**Review by fatchat — APPROVED** [review]

**Pull request merged**
