### PR TITLE
collapsible sidebar

### LINKED ISSUE #355: Make navigation bar on DDP UI collapsible
## Description
The Dalgo UI has a sidemenu for navigation on the left

image

We would like the user to be able to collapse it to get more screen space

## Goals
- [ ] Make the sidemenu collapsible (and expandable)

## Expected Outcome
A new control (small, clickable) on the sidemenu which toggles collapsed <-> expanded

## Acceptance Criteria
- [ ] Side menu should be collapsible

## Implementation Details
The frontend is a NextJS application. I will provide you with a login to our backend so that you don't have to run a backend on your own system

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo frontend

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
React, NextJS

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
Feature

### Sub Category
Frontend, Beginner friendly

### PR DESCRIPTION
**Pull request by huzaifmalik786**
## Summary
This PR closes #355 . A small toggle button has been added to the top of the navigation menu.
On closing the menu, users will still be able to navigate through different pages as small icons will still be visible.
I have used only the existing material UI library to achieve this with some custom styled components.

## Test Plan
[testing.webm](https://github.com/DalgoT4D/webapp/assets/100015095/bfd00343-efb5-4bfb-beab-8cf9751b1fb4)

### CODE REVIEW

**Comment by fatchat** [comment]
looking very nice @huzaifmalik786 

when it's closed it's perfect... but when it's open then there is a big gap between the top of the menu and the first menu item... you will probably have to put the toggle on the same line as "analysis"

**Comment by huzaifmalik786** [comment]
@fatchat If we keep them in a line, both the buttons are overlapping. Can we do like reduce the space between them instead of putting them in a line?
Screenshot 2024-02-02 194630

**Comment by fatchat** [comment]
Let’s see what ishan has to say

**Comment by fatchat** [comment]
how about at the bottom? under the privacy policy... might look good

**Comment by Ishankoradia** [comment]
> how about at the bottom? under the privacy policy... might look good

Hey @huzaifmalik786  @fatchat  i feel the icon should be a hamburger menu icon. We can put this menu icon to the left of the Dalgo logo. Like what gmail does . 
Open state
Screenshot 2024-02-03 at 9 13 02 AM

closed state
Screenshot 2024-02-03 at 9 13 46 AM


Also @huzaifmalik786  , please put all the svg icons you are using in the assets folder and import from there. Lets not use them directly in the components. Thanks.

**Comment by huzaifmalik786** [comment]
@Ishankoradia  @fatchat , cool then, I'll place it to the right of the logo and put the svg separately in the assets folder.

**Comment by huzaifmalik786** [comment]
[testing1.webm](https://github.com/DalgoT4D/webapp/assets/100015095/fd64778f-e9ae-403d-bb82-e7a0eb5441d4)
@Ishankoradia @fatchat please confirm if this looks good, I'll push the code then.

**Comment by Ishankoradia** [comment]
> @Ishankoradia @fatchat please confirm if this looks good, I'll push the code then.
> 
>  testing1.webm

looks good to me, thanks for contributing @huzaifmalik786 . Once our product team reviews, we will merge your PR.

**Review by fatchat — APPROVED** [review]

**Pull request merged**
