### PR TITLE
search added + floating save button

### PR DESCRIPTION
**Pull request by huzaifmalik786**
This PR solves #1040 #1068 #1065

### CODE REVIEW

**Comment by mdshamoon** [comment]
@huzaifmalik786 can you resolve merge conflicts and deep scan issues. Will review the PR after that

**Comment by huzaifmalik786** [comment]
@mdshamoon please check now.

**Comment by mdshamoon** [comment]
@huzaifmalik786 unit tests are failing now and deepscan issues are still there. Can you please check them?

**Comment by huzaifmalik786** [comment]
@mdshamoon , sorted! Please take a look now.
Thanks!

**Review by mdshamoon — CHANGES_REQUESTED** [review]
The type of the column changes in search. It should remain the same.

https://jam.dev/c/f339bf40-cf53-4d99-8abb-0a87d177c1d2

**Comment by mdshamoon** [comment]
> > The type of the column changes in search. It should remain the same.
> > https://jam.dev/c/f339bf40-cf53-4d99-8abb-0a87d177c1d2
> 
> Fixed!

@huzaifmalik786 now search and update is not working. Please check
 https://jam.dev/c/d4dd1fb1-0f0c-4b66-b582-8876f5ea45d1

**Comment by huzaifmalik786** [comment]
@mdshamoon , please check now, sorry for the bugs.

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
